name = input("What is your nombre?: ")
location = input("Where are you from?: ")
cocktail = input("Favorite happy hour drink: ")
music = input("What genre of music do you listen to?: ")
hobby = input("Favorite thing to do: ")
pet_peeve = input("What is your biggest pet peeve?: ")
num1 = input("How many pairs of shoes do you own?: ")
book = input("What types of books do you like to read?: ")
bucket_list = input("What is at the top of your bucket list?: ")
adjective = input("One word to best describe you: ")

print("Hello! my nombre is" + name)
print("My roots are based in " + location)
print("When I go to happy hour, I LOVE to drink " + cocktail)
print("I love to rock out to " + music, "in the shower every morning")
print("When I am not at work, I like to " + hobby)
print("My coworkers may not know it, but I REALLY cannot stand " + pet_peeve)
print("I am a closet hoarder of approximately " + num1, "pairs of shoes")
print("When I am not reading Bocchi's novel length emails, I love to read " + book)
print("One thing I really hope to do in the near future is " + bucket_list)
print("Many would describe me as" + adjective)

